### ISSUE TITLE
`/about`

### ISSUE THREAD

**Issue by franciszek-szeptycki** [franciszek-szeptycki/ecommerce#11]
opisz mi proszę(najlepiej tu w komentarzu)
jak ma wyglądać sekcja `/about`...

z tego co tu widzę to rozwiązałbym to tworząc jedno pole do pisania w `.md` z którego zaczytywałaby się treść do 
`Kim jesteśmy ?` i `Co nas wyróżnia ?`
+ 
kolejno dodawane elementy z których składałaby się sekcja `Kto należy do zespołu ?`

<img width="810" alt="Zrzut ekranu 2023-07-15 o 22 35 38" src="https://github.com/franciszek-szeptycki/ecommerce/assets/106173385/25229815-93c9-4dc2-9e93-592992616e71">

**Comment by Gabrli** [comment]
Wszystko dokładnie tak jak opisałeś
